# chooseCRANmirror(68)
# install.packages('stringi')
# install.packages("maps")
# install.packages("tidyverse")
# install.packages("jsonlite", dependencies = TRUE, repos = "http://cran.rstudio.com/")
# install.packages("dplyr")
# install.packages("rgdal")
# install.packages("dtwclust")
# install.packages("shiny")
# install.packages("leaflet")
# install.packages("DT")

library(shiny)
library(dtwclust)
library(tidyverse)
library(ggplot2)
library(maps)
library(leaflet)
library(dplyr)
library(rgdal)
library(lubridate)


setwd("D:/Formal/2. Projects/0. Comparison_and_Clustering_of_States/app")
runApp("./")
